# Generated by Django 4.1.7 on 2023-03-10 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=1000, verbose_name='last name')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='publication date')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('authors', models.ManyToManyField(blank=True, to='concepts.author', verbose_name='authors')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concepts.collection', verbose_name='collection')),
            ],
        ),
    ]
