# Generated by Django 4.1.7 on 2023-03-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0002_document_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='name'),
        ),
    ]
