# Generated by Django 4.1.7 on 2023-03-15 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0003_alter_collection_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500, verbose_name='name')),
                ('home_page', models.URLField(blank=True, verbose_name='home page')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=500, verbose_name='term')),
            ],
        ),
        migrations.CreateModel(
            name='SourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='link')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concepts.source', verbose_name='source')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concepts.term', verbose_name='term')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField(blank=True, verbose_name='words')),
                ('lemmas', models.TextField(blank=True, verbose_name='lemmas')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concepts.document', verbose_name='document')),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField(verbose_name='definition')),
                ('source_url', models.URLField(blank=True, verbose_name='URL')),
                ('accessed', models.DateTimeField(blank=True, null=True, verbose_name='accessed')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='concepts.source', verbose_name='source')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concepts.term', verbose_name='term')),
            ],
        ),
    ]
