# Generated by Django 4.1.7 on 2023-03-21 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0004_source_term_sourcelink_sentence_definition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='lemmas',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='words',
        ),
        migrations.AddField(
            model_name='sentence',
            name='text',
            field=models.TextField(default='No sentence text', verbose_name='text'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='index')),
                ('form', models.CharField(max_length=500, verbose_name='form')),
                ('lemma', models.CharField(max_length=500, verbose_name='lemma')),
                ('upos', models.CharField(max_length=10, verbose_name='UPOS')),
                ('xpos', models.CharField(max_length=10, verbose_name='XPOS')),
                ('features', models.CharField(blank=True, max_length=500, verbose_name='features')),
                ('head', models.IntegerField(verbose_name='head')),
                ('deprel', models.CharField(blank=True, max_length=500, verbose_name='deprel')),
                ('misc', models.CharField(blank=True, max_length=500, verbose_name='misc')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concepts.sentence', verbose_name='sentence')),
            ],
        ),
    ]
