# Generated by Django 4.1.7 on 2023-03-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0006_remove_document_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='head',
            field=models.IntegerField(null=True, verbose_name='head'),
        ),
    ]
