# Generated by Django 4.1.7 on 2023-03-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0007_alter_token_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='lemmas',
            field=models.TextField(default='uninitialized', verbose_name='lemmas'),
            preserve_default=False,
        ),
    ]
