# Generated by Django 4.1.7 on 2023-03-30 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0008_sentence_lemmas'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='source_name',
            field=models.CharField(default='Category', max_length=500, verbose_name='source name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='definition',
            name='accessed',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='accessed'),
        ),
        migrations.AlterField(
            model_name='token',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='concepts.sentence', verbose_name='sentence'),
        ),
    ]
