# Generated by Django 4.1.7 on 2023-08-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0009_definition_source_name_alter_definition_accessed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='priority'),
        ),
    ]
