# Generated by Django 4.1.7 on 2023-11-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0010_collection_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='query')),
                ('count', models.IntegerField(default=1, verbose_name='count')),
            ],
        ),
    ]
