# Generated by Django 4.2.10 on 2024-02-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0011_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='count',
            field=models.IntegerField(default=0, verbose_name='count'),
        ),
    ]
